<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
              <div class="alert alert-block alert-info">
                <h4>Recupere sua senha</h4>
                <p>
                  Um link de redefinição será enviado para seu e-mail. Verifique a caixa de SPAM, por favor
                </p>
              </div>
              <form class="form-horizontal">
                  <div class="form-group">
                    <label for="username" class="col-sm-3 control-label">Username:</label>
                    <div class="col-sm-8">
                      <input type="text" class="form-control" name="username" id="username" placeholder="Usuário">
                    </div>
                  </div>


                  <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-8">
                      <button type="submit" class="btn btn-success">Enviar link de redefinição</button>
                    </div>
                  </div>
              </form>
            </div>
        </div>
    </div>
</div>
